### ISSUE TITLE
PDF for Public works

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/TrashTalk#153]
Submit tool request to Public Works (PW)
 1. Create HTML form of tool request form
 2. Utilize [python-pdf/pydf](https://pypi.python.org/pypi/python-pdf) to convert from html to pdf
 3. Email PDF to Public Works

**Comment by TangoYankee** [comment]
Windows Error: 
 a. I am using Python 3.6.5 in Windows x64
 b. The error appears to relate to settings in [subprocess]
 c. Using wkhtmltopdf directly in the terminal successfully converts a trashtalk webpage into a webpage. 
(https://docs.python.org/3/library/subprocess.html) while using [wkthmltopdf](https://wkhtmltopdf.org/)
```
>>> import pydf
>>> pdf = pydf.generate_pdf('<h1>this is html<h1>')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\pydf\wkhtmltopdf.py", line 121, in generate_pdf
    return gen_pdf(html_file.name, cmd_args)
  File "C:\Program Files\Python36\lib\site-packages\pydf\wkhtmltopdf.py", line 105, in gen_pdf
    _, stderr, returncode = execute_wk(*cmd_args)
  File "C:\Program Files\Python36\lib\site-packages\pydf\wkhtmltopdf.py", line 22, in execute_wk
    p = subprocess.Popen(wk_args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application
```

**Comment by lizbeth58** [comment]
It seems the issue is that windows isn't getting the full path to the executable in the subprocess call.
`File "C:\Program Files\Python36\lib\site-packages\pydf\wkhtmltopdf.py", line 22, in execute_wk
    p = subprocess.Popen(wk_args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)`

https://stackoverflow.com/questions/912830/using-subprocess-to-run-python-script-on-windows

https://stackoverflow.com/questions/25651990/oserror-winerror-193-1-is-not-a-valid-win32-application#25652030

**Comment by TangoYankee** [comment]
I'm unable to resolve the issue. I'm considering bypassing python-pdf and running wkhtmltopdf as a python subprocess. Python-pdf works by passing raw html and outputting a pdf. However, we only really need a process that turns a webpage into a pdf. Wkhtmltopdf already does this.

Rough draft of code: (before substituting in proper references and such)
```
>>> webpage = "http://127.0.0.1:8000/cleanups/20/ "
>>> file_name = "public_works.pdf"
>>> wkhtmltopdf = 'wkhtmltopdf.exe '
>>> subprocess.run(wkhtmltopdf+webpage+file_name)
```
To-Do List:
 1. load wkhtmltopdf.exe into project
 2. reference location using settings/static
 3. create template for file names based on values from database
 4. create template for file locations to save pdfs
     a. manage saving/modify/deleting pdfs to avoid clutter
 5. create function to email pdfs to public works
 6. set email value in settings

**Comment by mosdevly** [comment]
Just checking in for the minute but wanted to acknowledge and let you know I'll get back to you this weekend.
