### ISSUE TITLE
Known Issue: AttributeError: 'NullSession' object has no attribute 'query'

### ISSUE THREAD

**Issue by mosdevly** [openoakland/TrashTalk#2]
It's already known and noted in the code, so posting this for a fix!

This only seems to occur right now when there's a clean database with no data to query (users or cleanups). 

**Steps to reproduce:**

* Fire up app locally
* Click on "Continue as Unregistered"
* 500 Internal Server Error

**Problem:**

The view doesn't check whether there are any clean-ups to list. When there aren't any, the session isn't populated and thus there's nothing to `query` (NullSession).

**Stacktrace:**
```
[2017-05-27 12:46:39,165] ERROR in app: Exception on /active_clean_ups [GET]
Traceback (most recent call last):

...[snip]...  

File "/home/projects/TrashTalk/trashtalk/views.py", line 148, in viewall_cleanup
    cleans = session.query(Cleanup).all()  # Look at all of the cleanups
  File "/home/.virtualenvs/trashtalk/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'NullSession' object has no attribute 'query'
127.0.0.1 - - [27/May/2017 12:46:39] "GET /active_clean_ups HTTP/1.1" 500 -
```
Relevant line of code from views.py L148:
```
 #    if session.query(Cleanup).count(): #commented out if/then is meant for when there are no cleanups
    cleans = session.query(Cleanup).all()
```

**Comment by mosdevly** [comment]
Related: Same issue for registering a brand new user. 

**Steps to reproduce**:

* Go to homepage
* Click "Sign-up"
* Fill out form and hit submit

**Problem**:
The query for validating users is empty (NullSession) on a fresh site.

**Stacktrace**:
```
[2017-05-27 13:03:56,919] ERROR in app: Exception on /create_account [POST]
Traceback (most recent call last):
 ...[snip]...
  File "/home/projects/TrashTalk/trashtalk/views.py", line 119, in create_account
    if not session.query(User).filter(User.username == new_name).count():
  File "/home/.virtualenvs/trashtalk/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'NullSession' object has no attribute 'query'
127.0.0.1 - - [27/May/2017 13:03:56] "POST /create_account HTTP/1.1" 500 -
```
I'll push a PR today that will take care of this! The code comments throughout are really great and make spotting/fixing things simpler.
