### ISSUE TITLE
current_app.config error

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/TrashTalk#53]
### Error from current_app.config
- I get this error from [googesheets.py](https://github.com/openoakland/TrashTalk/blob/master/trashtalk/google_sheets.py) and [seeclickfix.py](https://github.com/openoakland/TrashTalk/blob/master/trashtalk/seeclickfix.py) when using **current_app.config['VARIABLE_FROM_SETTINGS']**
```
Traceback (most recent call last):
  File "C:/Users/miller.tim/TrashTalk/trashtalk/run.py", line 30, in <module>
    app = app_factory('trashtalk.settings.Development')
  File "C:\Users\miller.tim\TrashTalk\trashtalk\factories.py", line 24, in app_factory
    register_all_blueprints(app)
  File "C:\Users\miller.tim\TrashTalk\trashtalk\factories.py", line 44, in register_all_blueprints
    mod = import_string(view)
  File "C:\Python27\lib\werkzeug\utils.py", line 418, in import_string
    __import__(import_name)
  File "C:\Users\miller.tim\TrashTalk\trashtalk\views\cleanups.py", line 8, in <module>
    from trashtalk.google_sheets import send_to_sheet
  File "C:\Users\miller.tim\TrashTalk\trashtalk\google_sheets.py", line 13, in <module>
    GOOGLE_SHEETS_VALIDATION = current_app.config['GOOGLE_SHEETS_VALIDATION']
  File "C:\Python27\lib\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Python27\lib\werkzeug\local.py", line 306, in _get_current_object
    return self.__local()
  File "C:\Python27\flask\globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
```

**Comment by mosdevly** [comment]
Ah ok. 

This occurs when the app context isn't ready, but it's being requested. Let's get your current PR merged and then I'll take a look at the error. I can't reproduce it locally so I think it's a product of the changes made.
